### ISSUE TITLE
KeyError: 'CALL_FUNCTION_VAR'

### ISSUE THREAD

**Issue by mhnamaki** [gems-uff/noworkflow#124]
Hello,
I have python 3.7.1 on Mac OS High Sierra.
I have followed the instructions for installation and installed it with [all] option.
However, when I type "now --help", I'm getting the following error in the interpreter.py:

 ```
opmap["CALL_FUNCTION"], opmap["CALL_FUNCTION_VAR"],
KeyError: 'CALL_FUNCTION_VAR'
```

Moreover, I have tried to install it for jupyter notebook too:
Once I type "jupyter nbextension install --py --sys-prefix noworkflow", I'm getting the same error:
   
```
opmap["CALL_FUNCTION"], opmap["CALL_FUNCTION_VAR"],
KeyError: 'CALL_FUNCTION_VAR'

```
Is it due to my Python version? which version should I use for this to work?

Best,
Mohammad

**Comment by JoaoFelipe** [comment]
Hi Mohammad,

noWorkflow 1 works up to Python 3.5. For Python 3.7, you can use the branch 2.0-alpha

**Comment by mhnamaki** [comment]
Hello,
Thanks :).
