### ISSUE TITLE
Conflicts when loading noworkflow Jupyter extension

### ISSUE THREAD

**Issue by hecking** [gems-uff/noworkflow#125]
I tried to load the noworkflow extension for Jupyter notebook but there seems to be a conflicting option --content-engine

`%load_ext noworkflow
import noworkflow.now.ipython as nip`

`---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-1-2b6f09596057> in <module>
----> 1 get_ipython().run_line_magic('load_ext', 'noworkflow')
      2 import noworkflow.now.ipython as nip`

...

`ArgumentError: argument --content-engine: conflicting option string: --content-engine`

Are there any ideas what went wrong?

**Comment by JoaoFelipe** [comment]
Thanks for reporting the bug!
It should work now.
