### ISSUE TITLE
Failed to Upgrade to 2.0

### ISSUE THREAD

**Issue by YuzeLou** [gems-uff/noworkflow#127]
I tried `pip install --upgrade  noworkflow[all]` in Python 3.7.5.

Got: `Requirement already up-to-date: noworkflow[all] in ./env/lib/python3.7/site-packages (1.12.0)`

How can I upgrade it to 2.0?

**Comment by JoaoFelipe** [comment]
Currently, 2.0 is only available through git in the 2.0-alpha branch. Follow these steps to install it:

Clone the repository:
`git clone https://github.com/gems-uff/noworkflow.git` 

Checkout branch:
```
cd noworkflow
git checkout 2.0-alpha
```

Install it:
`pip install -e capture`
