### ISSUE TITLE
SqlAlchemy warnings

### ISSUE THREAD

**Issue by braganholo** [gems-uff/noworkflow#134]
When running version 1.0 I get warnings in the command now run: 

(now-env) C:\Users\user\workspace>now run main.py
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Trial.variable_usages to refer to viewonly relationship
VariableUsage.trial should include sync_backref=False set on the
Trial.variable_usages relationship.  (this warning may be suppressed
after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
VariableUsage.trial to refer to viewonly relationship
Trial.variable_usages should include sync_backref=False set on the
VariableUsage.trial relationship.  (this warning may be suppressed
after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Trial.file_accesses to refer to viewonly relationship FileAccess.trial
should include sync_backref=False set on the Trial.file_accesses
relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Trial.variable_dependencies to refer to viewonly relationship
VariableDependency.trial should include sync_backref=False set on the
Trial.variable_dependencies relationship.  (this warning may be
suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
VariableDependency.trial to refer to viewonly relationship
Trial.variable_dependencies should include sync_backref=False set on
the VariableDependency.trial relationship.  (this warning may be
suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Trial.inherited to refer to viewonly relationship
Trial.bypass_children should include sync_backref=False set on the
Trial.inherited relationship.  (this warning may be suppressed after
10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Trial.parent to refer to viewonly relationship Trial.children should
include sync_backref=False set on the Trial.parent relationship.
(this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Trial.object_values to refer to viewonly relationship
ObjectValue.trial should include sync_backref=False set on the
Trial.object_values relationship.  (this warning may be suppressed
after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
Activation.target_variables to refer to viewonly relationship
VariableDependency.target_activation should include sync_backref=False
set on the Activation.target_variables relationship.  (this warning
may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
c:\users\user\now-env\lib\site-packages\sqlalchemy\orm\relationships.py:1998:
SAWarning: Setting backref / back_populates on relationship
ObjectValue.activation to refer to viewonly relationship
Activation.object_values should include sync_backref=False set on the
ObjectValue.activation relationship.  (this warning may be suppressed
after 10 occurrences)

**Comment by JoaoFelipe** [comment]
Closing issue related to version 1.0
