### ISSUE TITLE
The id column in the database does not express anymore the order in which the element appears

### ISSUE THREAD

**Issue by leomurta** [gems-uff/noworkflow#30]
Previous versions of noWorkflow assumed that the id column in the database reflects the order in which functions are activated, arguments are passed, and so on. After the change to store data in batch, this property got lost. Not sure if it is important to keep this property or not, but this should be checked. 

The graph visualization, for instance, processes function activations ordered by id. I am changing it to order by start time. However, it is worth it to search for other "order by id" in the project and evaluate possible side effects. Arguments may need to have an extra field to express the order they appear.

**Comment by JoaoFelipe** [comment]
After #63, the argument id is incremented in order. An explicit column for it is not necessary anymore
