### ISSUE TITLE
tests fails

### ISSUE THREAD

**Issue by aspinuso** [gems-uff/noworkflow#41]
Installed from pip and running with python 2.7.6.

  File "/User/lib/python2.7/site-packages/noworkflow/now/prov_definition/function_visitor.py", line 89, in extract_disasm
    self.metascript['code'], self.metascript['path'], 'exec')
  File "/noworkflow/tests/example1.py", line 22
    print 40
           ^
SyntaxError: invalid syntax

**Comment by JoaoFelipe** [comment]
Thank you for reporting this issue!

It was a bug in the python 'compile' function. When we imported print_function from __future__, the 'compile' tried to used python 3.x syntax.

**Comment by JoaoFelipe** [comment]
The new version with the fix and the possibility to look at the data on ipython notebook is already on PyPI
