### ISSUE TITLE
Cell Magic for IPython Notebook

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/noworkflow#46]
Support cell magic for ipython notebook:
Example
```python
In [1]: my_var = 2
In [2]: %%now --name script1 $my_var 30
   ...: import sys
   ...: print(sys.argv[1])
   ...: print(sys.argv[2])
2
30
Out [2]: <Trial 1>
```
This should run the code in the cell using noworkflow and return a trial object.
The default visualization of a trial object is an activation graph using ipython notebook.

**Comment by fchirigati** [comment]
Nice!

On Wed, Mar 25, 2015 at 11:37 PM, João Felipe N. Pimentel <
notifications@github.com> wrote:

> Support cell magic for ipython notebook:
> Example
>
> In [1]: my_var = 2
> In [2]: %%now --name script1 $my_var 30
>    ...: import sys
>    ...: print(sys.argv[1])
>    ...: print(sys.argv[2])230
> Out [2]: <Trial 1>
>
> This should run the code in the cell using noworkflow and return a trial
> object.
> The default visualization of a trial object is an activation graph using
> ipython notebook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gems-uff/noworkflow/issues/46>.
>



-- 
Fernando Chirigati
Research Assistant and Doctoral Candidate at NYU
http://bigdata.poly.edu/~fchirigati/ <http://vgc.poly.edu/~fchirigati/>
