### ISSUE TITLE
IPython Required?

### ISSUE THREAD

**Issue by dakoop** [gems-uff/noworkflow#47]
I think that the `.now.ipython` import in `noworkflow/__init__.py` means that IPython is required to run noWorkflow conflicting the README. However, I tried moving that import inside the `load_ipython_extension` method, and that did allow the help message to be printed without IPython installed.

**Comment by JoaoFelipe** [comment]
Fixed! IPython is not required for running noWorkflow
Thank you for reporting this bug!
