### ISSUE TITLE
Prolog name rule mix access id with activation id

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/noworkflow#57]
Add prefix to access id for disambiguation

**Comment by leomurta** [comment]
What about using hash to uniquely identify trials? We can have a local id mapped to the hash to make the usage easier (like Hg does).

**Comment by JoaoFelipe** [comment]
I think it would work. How should we calculate the hash? Using the existing script hash will cause conflicts. Maybe the start and end times?

**Comment by leomurta** [comment]
You need to get everything that make that version unique. script + environment + modules + files + ... but it may be slow. Double check if it is worth it...

**Comment by JoaoFelipe** [comment]
Thinking again, using hash for trials won't help with this issue. The conflict here is between activation id and access id:

```Prolog
?- changed(1, File)
File = 'open'
false.
```

It only occurs in the first trial. In the second trial it is ok:
```Prolog
?- changed(2, File)
File = 'output.png'
false.
```
The File id in the second trial is unique, but it matches the 'open' activation in the first trial.

I will keep the commited workaround (at least for now), but using hash for trials may be a good addition
