### ISSUE TITLE
Work with ids during execution collection

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/noworkflow#63]
Currently, noWorkflow uses a "complex" data structure during execution: the Activation object has a list of children activations, a list of Object Values (for arguments, and globals), a list of File Access.

When we save it, we have to navigate the whole activation stack in order to set the actual id and save the activations in the correct order. 

It makes it harder to add features such as partial saving the data, since it has a very specific order  to save.

We could use something simpler that calculates its __id__ during the execution and just store it as is.

In this issue, I propose to stop using a global __id__ as primary key of Activation, ObjectValue, FileAccess and use restart the __id__ for every trial and use the combination __trial_id__, __id__ 

It is already implemented at the ObjectStore class for Program Slicing variables, dependencies and usages, so it won't be hard to adapt to Profiler.

However, this change will break all the existing databases, and may break other parts of the code.

**Comment by braganholo** [comment]
I don't think breaking old databases is a serious issue at this point. In the worst case, it is always possible to implement a migration to the new schema.
